### ISSUE TITLE
NVIDIA Jetson AGX Orin running Balena unable to detect SD Cards / USB devices

### ISSUE THREAD

**Issue by treygilliland** [balena-os/balena-jetson-orin#213]
We have Balena installed on NVIDIA Jetson AGX Orin Dev Kit and it seems it is unable to detect when a USB device / SD card has been plugged in. We do not have this issue on the same device running Ubuntu instead of Balena.

Plugging in a device results in the device receiving power but not showing up anywhere on the Host OS. Here is what we have tried:

inserted sd after boot:
- ran dmesg to look for corresponding messages. no changes when inserting sd card
- lspci shows “SD Host controller: Genesys Logic, Inc GL9755 SD Host Controller”
- lsblk -f does not show the block device

inserted sd card before boot:
- same results as above

inserted same sd card into another NVIDIA Jetson Orin AGX Devkit running ubuntu not balenaOS:
- sd card block device shows up as expected

similar results with USB devices:
lsusb output on Balena Orin:
```
Bus 004 Device 001: ID 1d6b:0003 Linux 5.14.21-yocto-standard xhci-hcd xHCI Host Controller
Bus 003 Device 001: ID 1d6b:0002 Linux 5.14.21-yocto-standard xhci-hcd xHCI Host Controller
Bus 002 Device 001: ID 1d6b:0003 Linux 5.14.21-yocto-standard xhci-hcd xHCI Host Controller
Bus 001 Device 002: ID 8087:0026  
Bus 001 Device 001: ID 1d6b:0002 Linux 5.14.21-yocto-standard xhci-hcd xHCI Host Controller
```

lsusb output on Ubuntu Orin:
```
Bus 002 Device 002: ID 0bda:0420 Realtek Semiconductor Corp. 4-Port USB 3.0 Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1a2c:4324 China Resource Semico Co., Ltd 
Bus 001 Device 003: ID 0bda:5420 Realtek Semiconductor Corp. 4-Port USB 2.0 Hub
Bus 001 Device 002: ID 13d3:3549 IMC Networks Bluetooth Radio
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Bus 001 Device 004 is my keyboard, everything else shows by default.

**Comment by acostach** [comment]
Hi, just to clarify, this happens in the hostOS, right, and not in a container?

Could you also please tell me which ports you've tried? There are two near the eth port, another two near the 40 pin header and another usb-c on that same side. None of them work?

**Comment by acostach** [comment]
On my devkit I can use the usb ports on both sides and the sd-card reader is detected successfully from the hostOS. Maybe you are using a different type of AGX Orin module?

**Comment by treygilliland** [comment]
@acostach Thanks for the replies! I can confirm this is on the host OS. None of the ports register. Would you mind sharing your lsusb output for when you have a usb device connected? 

It also would be helpful if you have any version / diagnostic info if possible :)

**Comment by acostach** [comment]
@treygillilansure, sure, I clean flashed the AGX Orin Devkit with v2.114.19+rev1 and the latest master of jetson-flash and here's dmesg + lsusb with a USB SD-CARD adapter: https://gist.github.com/acostach/8705f302408d798ba39a56f760f84db3

It worked fine and I could mount the contents of the stick.

Next, I plugged the sd-card from the USB SD adapter directly in the AGX Orin's sd-card slot:

```
root@90c1085:~# dmesg | tail
[  310.906819] mmc1: card never left busy state
[  310.906844] mmc1: error -110 whilst initialising SD card
[  311.369284] mmc1: new ultra high speed SDR104 SDHC card at address e624
[  311.370121] mmcblk1: mmc1:e624 SP32G 29.7 GiB 
[  311.380432] GPT:Primary header thinks Alt. header is not at the end of the disk.
[  311.380437] GPT:5218303 != 62333951
[  311.380439] GPT:Alternate GPT header not at the end of the disk.
[  311.380440] GPT:5218303 != 62333951
[  311.380441] GPT: Use GNU Parted to correct GPT errors.
[  311.380460]  mmcblk1: p1 p2 p3 p4 p5 p6 p7 p8 p9 p10

root@90c1085:~# umount /tmp/mnt/
root@90c1085:~# mount /dev/mmcblk1p9 /tmp/mnt/                                                                                                                                                                     
root@90c1085:~# ls /tmp/mnt/
lost+found  machine-id  remove_me_to_reset  root-overlay
```

**Comment by acostach** [comment]
Is your module 32 or 64GB RAM? The module currently supported by the cloud images is the original one, with 32GB RAM

**Comment by acostach** [comment]
I see.. let us know if updating to the latest version solves the problem
