### ISSUE TITLE
photon-xavier-nx/photon-orin-nano/photon-orin-nx support

### ISSUE THREAD

**Issue by dremsol** [balena-os/balena-jetson-orin#293]
According to following [release notes](https://connecttech.com/ftp/Drivers/L4T-Release-Notes/Jetson-Orin-NX-Orin-Nano/ORIN-NX-NANO-35.3.1.pdf) it should be feasible to support both `photon-orin-nano` & `photon-orin-nx` devices with the photon carrier.

These [release notes](https://connecttech.com/ftp/Drivers/L4T-Release-Notes/Jetson-Xavier-NX/XAVIER-NX-35.3.1.pdf) suggest support for the `photon-xavier-nx`.

**Comment by acostach** [comment]
@dremsol for the Orin NX and Orin Nano, if you have the carrier board can you check if switching the dtb from the dashboard makes them usable with the standard Devkit images? The location for placing the dtb is the same, /mnt/sysroot/active/current/boot/

**Comment by dremsol** [comment]
Currently we only have the Jetson Orin Nano Devkit (NVME) available.

**Comment by acostach** [comment]
Closing this ticket for now, feel free to re-open if the kernel device-tree is the only change necessary for the Orin Nano or Orin NX to work with the Devkit images
